{
 "title": "MyHeat devices",
 "description": "Dashboard for system-controlled equipment https://myheat.net.\nThese are various heating equipment, boilers, pumps, sensors, often used in private homes.",
 "tags": [
  "iot",
  "myheat"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "electricity_tariff_1", "label": "Тариф на электричество 1", "query": "4.14" },
   { "name": "electricity_tariff_2", "label": "Тариф на электричество 2", "query": "4.21" },
   { "name": "heater_kwt", "label": "Суммарная мощность котла в кВт", "query": "9" }
  ]
 },
 "panels": [
  { "title": "Общие показания", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Дом",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myheat_env_temp_current", "legendFormat": "Помещение" }
   ]
  },
  {
   "title": "Дом Avg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "myheat_env_temp_current", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myheat_env_heat_demand", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Улица",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myheat_dev_weather_temp", "legendFormat": "Улица" }
   ]
  },
  {
   "title": "Улица Avg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "myheat_dev_weather_temp", "legendFormat": "__auto" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Дом Min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    { "expr": "myheat_env_temp_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Улица Min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "myheat_dev_weather_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myheat_env_temp_target", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Дом Max",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "myheat_env_temp_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Улица Max",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "myheat_dev_weather_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Затраты (Период)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(myheat_env_heat_tariff_seconds_total{tariff=\"1\"}[$__range]) / 60 / 60) * $heater_kwt * $electricity_tariff_2",
     "legendFormat": "День"
    },
    {
     "expr": "(increase(myheat_env_heat_tariff_seconds_total{tariff=\"2\"}[$__range]) / 60 / 60) * $heater_kwt * $electricity_tariff_2",
     "legendFormat": "Ночь"
    },
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Затраты (Месяц)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(myheat_env_heat_tariff_seconds_total{tariff=\"1\"}[7d]) / 60 / 60 / 7) * $heater_kwt * $electricity_tariff_1 * 30",
     "legendFormat": "День"
    },
    {
     "expr": "(increase(myheat_env_heat_tariff_seconds_total{tariff=\"2\"}[7d]) / 60 / 60 / 7) * $heater_kwt * $electricity_tariff_2 * 30",
     "legendFormat": "Ночь"
    },
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Энергия (Месяц)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(myheat_env_heat_tariff_seconds_total{tariff=\"1\"}[30d]) / 60 / 60) * $heater_kwt",
     "legendFormat": "День"
    },
    {
     "expr": "(increase(myheat_env_heat_tariff_seconds_total{tariff=\"2\"}[30d]) / 60 / 60) * $heater_kwt",
     "legendFormat": "Ночь"
    },
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Нагрев",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "myheat_env_heat_demand", "legendFormat": "Состояние" }
   ]
  },
  {
   "title": "Состояние системы",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "targets": [
    { "expr": "myheat_dev_severity", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Графики температур", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Температура помещения",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(myheat_env_temp_current[3m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Температура на улице",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg_over_time(myheat_dev_weather_temp[15m])",
     "legendFormat": "Температура"
    }
   ]
  }
 ]
}